https://f-droid.org/F-Droid.apk
https://f-droid.org/repo/net.gsantner.markor_124.apk
https://f-droid.org/repo/com.nutomic.syncthingandroid_4279.apk
https://f-droid.org/repo/org.schabi.newpipe_973.apk
https://f-droid.org/repo/com.foobnix.pro.pdf.reader_4085.apk
https://f-droid.org/repo/org.telegram.messenger_23605.apk
https://f-droid.org/repo/com.simplemobiletools.musicplayer_86.apk
https://f-droid.org/repo/com.simplemobiletools.gallery.pro_345.apk
https://f-droid.org/repo/com.simplemobiletools.filemanager.pro_107.apk
https://f-droid.org/repo/ml.docilealligator.infinityforreddit_70.apk
https://f-droid.org/repo/de.baumann.browser_116.apk
https://f-droid.org/repo/com.aurora.store_37.apk
https://snaptube.en.uptodown.com/android/download
https://f-droid.org/repo/com.kunzisoft.keepass.libre_83.apk


